Repository bobluppes/graaf, pull requests merged in 2023-08, with the labels that each got.

#64 breaking-change: Report traversed edges instead of vertices
  include/graaflib/algorithm/graph_traversal.h
  include/graaflib/algorithm/graph_traversal.tpp
  test/graaflib/algorithm/graph_traversal_test.cpp
Labels: enhancement, breaking-change

#65 breaking-change: Re-use graph traversal in bfs_shortest_path
  codecov.yml
  include/graaflib/algorithm/graph_traversal.h
  include/graaflib/algorithm/graph_traversal.tpp
  include/graaflib/algorithm/shortest_path.tpp
  test/graaflib/algorithm/graph_traversal_test.cpp
  test/graaflib/algorithm/shortest_path_test.cpp
Labels: breaking-change, refactor

#67 Enhancement: Catch negative edge weights in dijkstra
  include/graaflib/algorithm/shortest_path.tpp
  test/graaflib/algorithm/shortest_path_test.cpp
Labels: enhancement

#71 Enhancement: Catch negative edge weights in tree-version dijkstra
  include/graaflib/algorithm/shortest_path.tpp
  test/graaflib/algorithm/shortest_path_test.cpp
Labels: enhancement

#74 add dockerFile && Dockerignore
  .Dockerignore
  Dockerfile
Labels: tooling

#73 docs: add documentation for BFS (#56)
  docs/docs/algorithms/traversal/breadth-first-search.md
Labels: documentation

#81 refactor: Remove usage of fmt in library #72
  include/graaflib/algorithm/shortest_path.tpp
Labels: refactor

#78 Work on Tarjan's SCC algorithm
  README.md
  docs/docs/algorithms/strongly-connected-components/_category_.json
  docs/docs/algorithms/strongly-connected-components/tarjan.md
  include/graaflib/algorithm/strongly_connected_components.h
  include/graaflib/algorithm/strongly_connected_components.tpp
  test/graaflib/algorithm/strongly_connected_components_test.cpp
Labels: enhancement

#82 Kruskal's Minimum Spanning Tree
  README.md
  docs/docs/algorithms/shortest-path/minimum_spanning_tree.md
  include/graaflib/algorithm/minimum_spanning_tree.h
  include/graaflib/algorithm/minimum_spanning_tree.tpp
  test/graaflib/algorithm/minimum_spanning_tree_test.cpp
Labels: enhancement

#84 Work on a_star_search
  README.md
  docs/docs/algorithms/shortest-path/a-star.md
  docs/docs/algorithms/shortest-path/bellman-ford.md
  include/graaflib/algorithm/shortest_path.h
  include/graaflib/algorithm/shortest_path.tpp
  test/graaflib/algorithm/shortest_path_test.cpp
Labels: enhancement
