Repository bobluppes/graaf, pull requests merged in 2023-06, with the labels that each got.

#30 docs: Switch from doxygen to docusaurus
  .gitattributes
  .github/workflows/documentation.yml
  README.md
  docs/.gitignore
  docs/Doxyfile
  docs/README.md
  docs/babel.config.js
  docs/docs/intro.md
  docs/docs/tutorial-basics/_category_.json
  docs/docs/tutorial-basics/some-other-page.md
  docs/docs/tutorial-basics/some-page.md
  docs/docusaurus.config.js
  docs/html/.gitignore
  docs/html/custom_header.html
  docs/package.json
  docs/sidebars.js
  docs/src/components/HomepageFeatures/index.tsx
  docs/src/components/HomepageFeatures/styles.module.css
  docs/src/css/custom.css
  docs/src/pages/index.module.css
  docs/src/pages/index.tsx
  docs/static/.nojekyll
  docs/static/img/docusaurus-social-card.jpg
  docs/static/img/docusaurus.png
  docs/static/img/favicon.ico
  docs/static/img/graaf.png
  docs/static/img/logo.svg
  docs/static/img/undraw_docusaurus_mountain.svg
  docs/static/img/undraw_docusaurus_react.svg
  docs/static/img/undraw_docusaurus_tree.svg
  docs/tsconfig.json
  docs/yarn.lock
Labels: documentation

#31 feat: Add support for weighted edges
  examples/dot_serialization/main.cpp
  examples/shortest_path/main.cpp
  include/graaflib/algorithm/graph_traversal.h
  include/graaflib/algorithm/graph_traversal.tpp
  include/graaflib/algorithm/shortest_path.h
  include/graaflib/algorithm/shortest_path.tpp
  include/graaflib/directed_graph.h
  include/graaflib/directed_graph.tpp
  include/graaflib/graph.h
  include/graaflib/graph.tpp
  include/graaflib/io/dot.h
  include/graaflib/io/dot.tpp
  include/graaflib/properties/vertex_properties.h
  include/graaflib/properties/vertex_properties.tpp
  include/graaflib/types.h
  include/graaflib/undirected_graph.h
  include/graaflib/undirected_graph.tpp
  test/graaflib/graph_test.cpp
  test/graaflib/graph_traits_test.cpp
  test/graaflib/io/dot_test.cpp
  test/graaflib/weighted_graph_test.cpp
Labels: enhancement, breaking-change

#32 docs: added sidebar for examples
  docs/docs/examples/Intro.md
  docs/docs/tutorial/intro.md
  docs/docs/tutorial/tutorial-basics/_category_.json
  docs/docs/tutorial/tutorial-basics/some-other-page.md
  docs/docs/tutorial/tutorial-basics/some-page.md
  docs/docusaurus.config.js
  docs/sidebars.js
Labels: documentation

#34 tooling: Added CI step to verify documentation
  .github/workflows/main-ci.yml
Labels: tooling

#35 Remove unweighted graph spec
  examples/dot_serialization/main.cpp
  examples/shortest_path/main.cpp
  include/graaflib/algorithm/graph_traversal.h
  include/graaflib/algorithm/graph_traversal.tpp
  include/graaflib/algorithm/shortest_path.h
  include/graaflib/algorithm/shortest_path.tpp
  include/graaflib/directed_graph.h
  include/graaflib/directed_graph.tpp
  include/graaflib/graph.h
  include/graaflib/graph.tpp
  include/graaflib/io/dot.h
  include/graaflib/io/dot.tpp
  include/graaflib/properties/vertex_properties.h
  include/graaflib/properties/vertex_properties.tpp
  include/graaflib/types.h
  include/graaflib/undirected_graph.h
  include/graaflib/undirected_graph.tpp
  test/graaflib/directed_graph_test.cpp
  test/graaflib/graph_test.cpp
  test/graaflib/graph_traits_test.cpp
  test/graaflib/io/dot_test.cpp
  test/graaflib/undirected_graph_test.cpp
  test/graaflib/weighted_graph_test.cpp
Labels: enhancement, breaking-change

#36 Add README to documentation
  docs/docs/examples/example-basics/dot-serialization-graph.png
  docs/docs/examples/example-basics/dot-serialization.md
  docs/docs/examples/example-basics/shortest-path-graph.png
  docs/docs/examples/example-basics/shortest-path.md
  docs/docs/examples/example-basics/shortest_path.png
Labels: documentation

#40 docs: Improve examples and algorithms in readme
  README.md
  docs/docs/algorithms/intro.md
  docs/docs/algorithms/shortest-path/_category_.json
  docs/docs/algorithms/shortest-path/bfs-based-shortest-path.md
  docs/docs/algorithms/traversal/_category_.json
  docs/docs/algorithms/traversal/breadth-first-search.md
  docs/docs/algorithms/traversal/depth-first-search.md
  docs/docs/quickstart/basics/_category_.json
  docs/docs/quickstart/basics/architecture.md
  docs/docs/quickstart/basics/creating-your-first-graph.md
  docs/docs/quickstart/basics/using-algorithms.md
  docs/docs/quickstart/installation/_category_.json
  docs/docs/quickstart/installation/alternative-methods.md
  docs/docs/quickstart/installation/installation.md
  docs/docs/quickstart/intro.md
  docs/docs/tutorial/tutorial-basics/_category_.json
  docs/docusaurus.config.js
  docs/sidebars.js
  docs/src/pages/index.tsx
  docs/static/img/graph_example.png
  include/README.md
Labels: documentation
