Repository bobluppes/graaf, pull requests merged in 2023-10, with the labels that each got.

#122 Updated readme.md
  README.md
Labels: documentation, hacktoberfest-accepted

#120 [TEST] Scenarios for fully connected and disconnected graphs
  test/utils/scenarios/scenarios.h
  test/utils/scenarios/scenarios.tpp
Labels: tests

#132 add stale workflow
  .github/workflows/stale.yml
Labels: tooling

#124 [TEST] Extract common test fixtures
  test/graaflib/algorithm/coloring/greedy_coloring_test.cpp
  test/graaflib/algorithm/cycle_detection/dfs_cycle_detection_test.cpp
  test/graaflib/algorithm/graph_traversal/breadth_first_search_test.cpp
  test/graaflib/algorithm/graph_traversal/depth_first_search_test.cpp
  test/graaflib/algorithm/minimum_spanning_tree/kruskal_test.cpp
  test/graaflib/algorithm/minimum_spanning_tree/prim_test.cpp
  test/graaflib/algorithm/shortest_path/a_star_test.cpp
  test/graaflib/algorithm/shortest_path/bellman_ford_test.cpp
  test/graaflib/algorithm/shortest_path/bfs_shortest_path_test.cpp
  test/graaflib/algorithm/shortest_path/dijkstra_shortest_path_test.cpp
  test/graaflib/algorithm/shortest_path/dijkstra_shortest_paths_test.cpp
  test/graaflib/algorithm/shortest_path/floyd_warshall_test.cpp
  test/graaflib/algorithm/strongly_connected_components/tarjan_test.cpp
  test/graaflib/algorithm/topological_sorting/dfs_topological_sorting_test.cpp
  test/graaflib/graph_test.cpp
  test/graaflib/weighted_graph_test.cpp
  test/utils/fixtures/fixtures.h
Labels: refactor, hacktoberfest-accepted

#138 added environment set up link
  README.md
Labels: documentation

#136 Adding new utils header containing "get_transposed_graph" function
  include/graaflib/algorithm/utils.h
  include/graaflib/algorithm/utils.tpp
  include/graaflib/graph.h
  include/graaflib/graph.tpp
  test/graaflib/algorithm/utils_test.cpp
  test/graaflib/graph_test.cpp
Labels: enhancement, hacktoberfest-accepted

#139 [ALGO]Bron-Kerbosch with pivoting
  README.md
  docs/docs/algorithms/clique-detection/_category_.json
  docs/docs/algorithms/clique-detection/bron_kerbosch.md
  include/graaflib/algorithm/clique_detection/bron_kerbosch.h
  include/graaflib/algorithm/clique_detection/bron_kerbosch.tpp
  test/graaflib/algorithm/clique_detection/bron_kerbosch_test.cpp
Labels: enhancement

#118 Feat : Added Welsh-Powell graph coloring algorithm
  README.md
  include/graaflib/algorithm/coloring/welsh_powell.h
  include/graaflib/algorithm/coloring/welsh_powell.tpp
  test/graaflib/algorithm/coloring/welsh_powell_test.cpp
  test/utils/fixtures/fixtures.h
Labels: enhancement, hacktoberfest-accepted

#141 [ALGO] Kosaraju's Algorithm
  README.md
  docs/docs/algorithms/strongly-connected-components/kosarajus.md
  docs/docs/algorithms/strongly-connected-components/tarjan.md
  include/graaflib/algorithm/strongly_connected_components/common.h
  include/graaflib/algorithm/strongly_connected_components/kosaraju.h
  include/graaflib/algorithm/strongly_connected_components/kosaraju.tpp
  include/graaflib/algorithm/strongly_connected_components/tarjan.h
  include/graaflib/algorithm/strongly_connected_components/tarjan.tpp
  test/graaflib/algorithm/strongly_connected_components/kosaraju_test.cpp
  test/graaflib/algorithm/strongly_connected_components/tarjan_test.cpp
Labels: enhancement, hacktoberfest-accepted

#152 Feat : Added Documentation for Welsh Powell Algorithm
  docs/docs/algorithms/coloring/welsh-powell.md
Labels: documentation, hacktoberfest-accepted

#156 Fixed broken image in README.md
  README.md
Labels: documentation, hacktoberfest-accepted

#154 Docs/corrections
  docs/.gitignore
  docs/docs/quickstart/basics/creating-your-first-graph.md
  docs/docs/quickstart/installation/alternative-methods.md
  docs/docs/quickstart/installation/installation.md
  docs/static/img/quickstart/Graph.png
Labels: documentation, hacktoberfest-accepted

#157 [BENCH] Bron-Kerbosch clique detection
  perf/graaflib/bron_kerbosch_benchmark.cpp
Labels: performance
