Repository bobluppes/graaf, pull requests merged in 2023-09, with the labels that each got.

#86 Docs for BFS-based shortest path search
  docs/docs/algorithms/shortest-path/bfs-based-shortest-path.md
  include/graaflib/algorithm/shortest_path.h
Labels: documentation

#93 Topological Sorting
  README.md
  docs/docs/algorithms/topological-sort/topological-sort.md
  include/graaflib/algorithm/topological_sorting.h
  include/graaflib/algorithm/topological_sorting.tpp
  test/graaflib/algorithm/topological_sorting_test.cpp
Labels: enhancement

#94 Work on greedy graph coloring.
  README.md
  docs/docs/algorithms/coloring/_category_.json
  docs/docs/algorithms/coloring/greedy-graph-coloring.md
  include/graaflib/algorithm/coloring/greedy_graph_coloring.h
  include/graaflib/algorithm/coloring/greedy_graph_coloring.tpp
  test/graaflib/algorithm/graph_coloring_test.cpp
Labels: enhancement

#96 DOCS DFS cycle detection
  docs/docs/algorithms/cycle-detection/dfs-based.md
Labels: enhancement

#99 [TOOL] Add Dependabot for GitHub actions
  .github/dependabot.yml
Labels: tooling

#97 Added the negative cycle detection in bellman ford
  include/graaflib/algorithm/shortest_path.tpp
  test/graaflib/algorithm/shortest_path_test.cpp
Labels: enhancement

#98 Floyd-Warshall algorithm
  docs/docs/algorithms/shortest-path/floyd-warshall.md
  include/graaflib/algorithm/shortest_path/floyd_warshall.h
  include/graaflib/algorithm/shortest_path/floyd_warshall.tpp
  test/graaflib/algorithm/floyd_warshall_test.cpp
Labels: enhancement

#79 Add cmake options for enabling and disabling builds
  CMakeLists.txt
Labels: tooling

#105 refactor: algorithm directory structure
  examples/shortest_path/main.cpp
  examples/transport/main.cpp
  include/graaflib/algorithm/cycle_detection/dfs_cycle_detection.h
  include/graaflib/algorithm/cycle_detection/dfs_cycle_detection.tpp
  include/graaflib/algorithm/graph_traversal.h
  include/graaflib/algorithm/graph_traversal/breadth_first_search.h
  include/graaflib/algorithm/graph_traversal/breadth_first_search.tpp
  include/graaflib/algorithm/graph_traversal/common.h
  include/graaflib/algorithm/graph_traversal/depth_first_search.h
  include/graaflib/algorithm/graph_traversal/depth_first_search.tpp
  include/graaflib/algorithm/minimum_spanning_tree/kruskal.h
  include/graaflib/algorithm/minimum_spanning_tree/kruskal.tpp
  include/graaflib/algorithm/minimum_spanning_tree/prim.h
  include/graaflib/algorithm/minimum_spanning_tree/prim.tpp
  include/graaflib/algorithm/shortest_path.h
  include/graaflib/algorithm/shortest_path.tpp
  include/graaflib/algorithm/shortest_path/a_star.h
  include/graaflib/algorithm/shortest_path/a_star.tpp
  include/graaflib/algorithm/shortest_path/bellman_ford.h
  include/graaflib/algorithm/shortest_path/bellman_ford.tpp
  include/graaflib/algorithm/shortest_path/bfs_shortest_path.h
  include/graaflib/algorithm/shortest_path/bfs_shortest_path.tpp
  include/graaflib/algorithm/shortest_path/common.h
  include/graaflib/algorithm/shortest_path/common.tpp
  include/graaflib/algorithm/shortest_path/dijkstra_shortest_path.h
  include/graaflib/algorithm/shortest_path/dijkstra_shortest_path.tpp
  include/graaflib/algorithm/shortest_path/dijkstra_shortest_paths.h
  include/graaflib/algorithm/shortest_path/dijkstra_shortest_paths.tpp
  include/graaflib/algorithm/strongly_connected_components/tarjan.h
  include/graaflib/algorithm/strongly_connected_components/tarjan.tpp
  include/graaflib/algorithm/topological_sorting/dfs_topological_sorting.h
  include/graaflib/algorithm/topological_sorting/dfs_topological_sorting.tpp
  test/graaflib/algorithm/coloring/greedy_coloring_test.cpp
  test/graaflib/algorithm/cycle_detection/dfs_cycle_detection_test.cpp
  test/graaflib/algorithm/graph_traversal/breadth_first_search_test.cpp
  test/graaflib/algorithm/graph_traversal/depth_first_search_test.cpp
  test/graaflib/algorithm/minimum_spanning_tree/kruskal_test.cpp
  test/graaflib/algorithm/minimum_spanning_tree/prim_test.cpp
  test/graaflib/algorithm/shortest_path/a_star_test.cpp
  test/graaflib/algorithm/shortest_path/bellman_ford_test.cpp
  test/graaflib/algorithm/shortest_path/bfs_shortest_path_test.cpp
  test/graaflib/algorithm/shortest_path/dijkstra_shortest_path_test.cpp
  test/graaflib/algorithm/shortest_path/dijkstra_shortest_paths_test.cpp
  test/graaflib/algorithm/shortest_path/floyd_warshall_test.cpp
  test/graaflib/algorithm/shortest_path_test.cpp
  test/graaflib/algorithm/strongly_connected_components/tarjan_test.cpp
  test/graaflib/algorithm/topological_sorting/dfs_topological_sorting_test.cpp
Labels: refactor

#110 fixed formatting in readme and changed the order to alphabetical
  README.md
Labels: documentation, hacktoberfest
